# The following fig.yml file starts up the agave_id service in single-tenant mode. It defaults to
# using an image, but you can also build from source if you prefer. You will need to endure that
# MULTI_TENANT=False is set in your local_settings.py file first.

agaveid:
  image: tacc/agave_id
  # Uncomment the following line (and comment the build line just above) to build from source
#  build: ../
  ports:
    - "8000:80"
  links:
    - ldap
  volumes:
    - ./apache-error.log:/var/log/apache2/error.log
    - ./apache-access.log:/var/log/apache2/access.log
    - ./django.log:/tmp/django.log
  environment:
    HOST_IP:

ldap:
  image: jstubbs/slapd
  environment:
    - LDAP_DOMAIN=agaveapi
    - LDAP_ORGANISATION="Agave"
    - LDAP_ROOTPASS=p@ssword
  ports:
    - "10389:389"
