# The following docker compose file starts up the pyprofiles-api service in multi-tenant mode. It defaults to
# using an image, but you can also build from source if you prefer. You will need to ensure that
# MULTI_TENANT=True is set in your local_settings.py file first.

agaveid:
  image: pyprofiles-api:develop
  # Uncomment the following line (and comment the build line just above) to build from source
#  build: ../
  ports:
    - "8000:80"
  links:
    - ldap
  environment:
    HOST_IP:

ldap:
  image: jstubbs/slapd
  environment:
    - LDAP_DOMAIN=agaveapi
    - LDAP_ORGANISATION="Agave"
    - LDAP_ROOTPASS=p@ssword
  ports:
    - "10389:389"